#!/usr/bin/env python3
"""Check that the committed Conda lockfiles match their source files."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SOURCE_FILES = (
    Path("environment.yml"),
    Path(".github/conda-lock/ci-dependencies.yml"),
)
SOURCE_HASH_FILE = Path(".github/conda-lock/source-files.sha256")
LOCKFILES = {
    "linux-64": Path(".github/conda-lock/conda-linux-64.lock"),
    "osx-arm64": Path(".github/conda-lock/conda-osx-arm64.lock"),
    "win-64": Path(".github/conda-lock/conda-win-64.lock"),
}
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")
PACKAGE_HASH_PATTERN = re.compile(r"[0-9a-f]{32}|[0-9a-f]{64}")


def compute_source_hash(repository_root: Path) -> str:
    """Hash paths, sizes, and contents to avoid ambiguous concatenations."""
    digest = hashlib.sha256()
    for relative_path in SOURCE_FILES:
        content = (repository_root / relative_path).read_bytes()
        digest.update(relative_path.as_posix().encode())
        digest.update(b"\0")
        digest.update(str(len(content)).encode())
        digest.update(b"\0")
        digest.update(content)
    return digest.hexdigest()


def validate_lockfile(repository_root: Path, platform: str, relative_path: Path) -> list[str]:
    errors: list[str] = []
    path = repository_root / relative_path
    if not path.is_file():
        return [f"{relative_path}: missing lockfile"]

    lines = path.read_text().splitlines()

    expected_header = [
        "# Generated by conda-lock.",
        f"# platform: {platform}",
    ]
    if lines[:2] != expected_header:
        errors.append(f"{relative_path}: invalid platform header")

    if len(lines) < 4 or not lines[2].startswith("# input_hash: "):
        errors.append(f"{relative_path}: missing input_hash")
    elif not SHA256_PATTERN.fullmatch(lines[2].removeprefix("# input_hash: ")):
        errors.append(f"{relative_path}: invalid input_hash")

    if len(lines) < 4 or lines[3] != "@EXPLICIT":
        errors.append(f"{relative_path}: missing @EXPLICIT marker")

    allowed_subdirectories = {"noarch", platform}
    package_count = 0
    for line_number, line in enumerate(lines[4:], start=5):
        if not line or line.startswith("#"):
            continue
        package_count += 1
        prefix = "https://conda.anaconda.org/conda-forge/"
        if not line.startswith(prefix) or "#" not in line:
            errors.append(f"{relative_path}:{line_number}: invalid package URL")
            continue
        package_path, package_hash = line[len(prefix) :].rsplit("#", 1)
        subdirectory = package_path.split("/", 1)[0]
        if subdirectory not in allowed_subdirectories:
            errors.append(f"{relative_path}:{line_number}: unexpected subdirectory " f"{subdirectory!r}")
        if not PACKAGE_HASH_PATTERN.fullmatch(package_hash):
            errors.append(f"{relative_path}:{line_number}: invalid package hash")

    if package_count == 0:
        errors.append(f"{relative_path}: lockfile contains no packages")

    return errors


def check(repository_root: Path) -> list[str]:
    errors: list[str] = []
    missing_sources = [str(path) for path in SOURCE_FILES if not (repository_root / path).is_file()]
    if missing_sources:
        errors.extend(f"{path}: missing source file" for path in missing_sources)
    else:
        actual_source_hash = compute_source_hash(repository_root)
        source_hash_path = repository_root / SOURCE_HASH_FILE
        expected_source_hash = source_hash_path.read_text().strip() if source_hash_path.is_file() else ""

        if not SHA256_PATTERN.fullmatch(expected_source_hash):
            errors.append(f"{SOURCE_HASH_FILE}: missing or invalid source hash")
        elif actual_source_hash != expected_source_hash:
            errors.append("Conda environment sources changed; regenerate the lockfiles and source fingerprint")

    for platform, relative_path in LOCKFILES.items():
        errors.extend(validate_lockfile(repository_root, platform, relative_path))

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--print-source-hash",
        action="store_true",
        help="print the current source hash for lockfile regeneration",
    )
    args = parser.parse_args()

    if args.print_source_hash:
        print(compute_source_hash(REPOSITORY_ROOT))
        return 0

    errors = check(REPOSITORY_ROOT)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        print(
            "Regenerate all lockfiles and update source-files.sha256 as documented in .github/conda-lock/README.md.",
            file=sys.stderr,
        )
        return 1

    print("Conda lockfiles are consistent with their source files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
